# These are supported funding model platforms

github: [mbround18] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mbround18 # Replace with a single Patreon username
ko_fi: mbround18 # Replace with a single Ko-fi username
custom: ["https://paypal.me/MichaelBruno"]
