name: Setup
author: mbround18
description: Setup for this repo
runs:
  using: "composite"
  steps:
    - name: Setup | Rust | Stable
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: clippy rustfmt
        targets: wasm32-unknown-unknown

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-setup-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Trunk
      uses: mbround18/trunk-rs@v1.1

    - run: cargo build
      shell: sh
