[tasks.thumbs]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "thumbnail-generator",
    "./"
]

[tasks.dev]
dependencies = [ "rustfmt" ]
install_crate = { crate_name = "trunk" }
workspace = false
command = "trunk"
args = [
    "serve",
    "--watch=./packages/gh-pagify/src",
    "./packages/gh-pagify/index.html"
]

[tasks.rustfmt]
workspace = false
command = "cargo"
args = [
    "fmt"
]

[tasks.clippy]
install_crate = { crate_name = "clippy" }
workspace = false
command = "cargo"
args = [
    "clippy"
]

[tasks.lint]
workspace = false
dependencies = [ "rustfmt", "clippy" ]
