[package]
name = "ssr-catalog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
# you can check the latest version here: https://crates.io/crates/yew
yew = { version = "0.21" , features = ["ssr"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
base64 = "0.21"
urlencoding = "2"
glob = "0"
tokio = { version = "1", features = ["full"] }
titlecase = "2"
wasm-bindgen = "0.2.88"
