[package]
name = "gh-pagify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# you can check the latest version here: https://crates.io/crates/yew
yew = "0.19"
yew-router = "0.16"
reqwasm = "0.4.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
gloo-console = "0.2.1"
gloo-utils = "0"
web-sys = "0"
markdown="0"
