[package]
name = "thumbnail-generator"
version = "0.1.0"
authors = ["mbround18 <12646562+mbround18@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3"
clap = "3"
serde = {version= "1", features = ["derive"]}
serde_json = "1"
webp = "0"
image = "0"
base64 = "0"
blake2 = "0"
