name: Rust

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/docs/**/*"
      - "**/*.info"
      - "**/*.preview.png"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/docs/**/*"
      - "**/*.info"
      - "**/*.preview.png"
env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-nd-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: trunk build ./packages/gh-pagify/index.html

      # Parser
      - name: Thumbnail Parser
        uses: ./.github/actions/parser

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-nd-test]
    environment: aws-s3
    if: github.event_name != 'pull_request'
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # <- Suggested to get all tags
          token: ${{ secrets.GH_TOKEN }} # <- This is required

      # Deps
      - name: Setup
        uses: ./.github/actions/setup

      - name: AWS CLI Install
        uses: unfor19/install-aws-cli-action@master

      # Release
      - name: Release 🚀
        uses: mbround18/auto@v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }} # <- This is for auto

      - name: Upload Assets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
        run: |
          # Build Release
          trunk build --release -d ./dist ./packages/gh-pagify/index.html

          # Upload Release
          aws                       \
            s3 sync                 \
            ./dist/                 \
            s3://mbruno-static-files/dnd-apps/vtt-apps/ \
            --request-payer requester
