name: Rust

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/docs/**/*"
      - "**/*.info"
      - "**/*.preview.png"
      - "README.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - "**/docs/**/*"
      - "**/*.info"
      - "**/*.preview.png"
env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-nd-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: trunk build ./packages/gh-pagify/index.html

      # Parser
      - name: Thumbnail Parser
        uses: ./.github/actions/parser

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-nd-test]
    environment: aws-s3
    if: github.event_name != 'pull_request'
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Deps
      - name: Setup
        uses: ./.github/actions/setup

      - name: AWS CLI Install
        uses: unfor19/install-aws-cli-action@master

      - name: Build Release
        run: make compile

      - name: Upload Assets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
        run: |
          aws                       \
            s3 sync                 \
            ./packages/gh-pagify/dist                 \
            s3://mbruno-static-files/dnd-apps/vtt-maps \
            --request-payer requester
