name: File Mod

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run Install
      run: cargo install --path ./dd2vtt-parserh
    - name: Run Parser
      run: dd2vtt-parser ./
