name: Rust

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/docs/**/*"
      - "**/*.info"
      - "**/*.preview.png"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/docs/**/*"
      - "**/*.info"
      - "**/*.preview.png"
env:
  NAME: "Rust Test"
  CARGO_TERM_COLOR: always

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-nd-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup | Rust | Nightly
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy rustfmt
          targets: wasm32-unknown-unknown

      - uses: actions/cache@v2
        name: Cache Cargo Files
        with:
          path: |
            target/release
            target/debug
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Install
        run: |
          cargo install --path ./packages/thumbnail-generator
          cargo install trunk

      - name: Run Parser
        run: thumbnail-generator ./

      - name: Build Pages
        run: trunk build --release -d ./docs ./packages/gh-pagify/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages
          folder: docs

      # - name: Commit
      #   run: |
      #     git config --global user.email "12646562+mbround18@users.noreply.github.com"
      #     git config --global user.name "mbround18"

      #     git pull
      #     git add --all
      #     git commit -am "Auto Generated"
      #     git push
